// export const GET_SCHEDULES_BY_ZONE = `
// {
//     schedules{
//         start
//         end
//         provider{
//         id
//         name
//         number
//         reception_zone{
//             id
//             Name
//             }
//         }
//         product_order
//         promise_date
//         full_day
//         }
//   }`;
